# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tmazan <tmazan@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/05/15 18:23:32 by tmazan            #+#    #+#              #
#    Updated: 2024/05/17 17:26:40 by tmazan           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
		gcc -Wall -Wextra -Werror -c ft_display_file.c -o ft_display_file.o
		gcc -Wall -Wextra -Werror ft_display_file.o -o ft_display_file

clean:
		rm -f ft_display_file.o

fclean: clean
		rm -f ft_display_file